### ISSUE TITLE
number of result pages

### ISSUE THREAD

**Issue by krolaper** [giaco8020/duckduckgo-search-api#1]
how many result pages are you processing? And then in your code, I looked, it’s not there

**Comment by krolaper** [comment]
You also need to add a proxy implementation.

**Comment by giaco8020** [comment]
Hi, thank you for your feedback. 
The API returns the first page of results, which includes about ~ 20 results per input.
I'm going to fix code adding proxy implementation and search filter by the end of April

**Comment by giaco8020** [comment]
I added proxy implementation and fixed the code. 
You can search only the first results page, which displays about 20 results.
